services:
  api:
    container_name: tickets_utpl
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./tailwind.config.ts:/app/tailwind.config.ts

      - /app/node_modules
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
