version: "3.9"

services:
  api:
    container_name: dashboard
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./src:/app/src
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
